---
- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Install Ruby"
  package:
    name: "{{ ruby_packages }}"
  register: ruby_install_ruby
  until: ruby_install_ruby is succeeded
  retries: 3
